import type { Complaint, User, Notification, Announcement, DashboardStats } from '@/types'
import { CATEGORIES } from './constants'

// Mock current user (for demo purposes)
export const MOCK_CITIZEN: User = {
  id: 'user-1',
  name: 'Shankar Patil',
  phone: '+91 93264 58912',
  email: 'shankar.patil@email.com',
  role: 'citizen',
  ward: 'Ward 15',
  zone: 'Zone 3',
  avatar: undefined,
  isVerified: true,
  aadhaarLinked: false,
  createdAt: '2024-06-15T10:00:00Z',
}

export const MOCK_OFFICER: User = {
  id: 'officer-1',
  name: 'R.K. Pawar',
  phone: '+91 98765 43210',
  email: 'rk.pawar@municipality.gov.in',
  role: 'officer',
  ward: 'Ward 15',
  zone: 'Zone 3',
  department: 'Roads',
  avatar: undefined,
  isVerified: true,
  aadhaarLinked: true,
  createdAt: '2022-03-01T10:00:00Z',
}

export const MOCK_ADMIN: User = {
  id: 'admin-1',
  name: 'Suresh Kumar',
  phone: '+91 99887 76655',
  email: 'admin@municipality.gov.in',
  role: 'admin',
  avatar: undefined,
  isVerified: true,
  aadhaarLinked: true,
  createdAt: '2021-01-01T10:00:00Z',
}

// Mock complaints
export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'complaint-1',
    displayId: 'CR-2026-00142',
    description: 'There is a large pothole on the main road near Shivaji signal. Multiple accidents have happened here. Especially dangerous during rain.',
    category: CATEGORIES[1], // Roads
    subcategory: CATEGORIES[1].subcategories[0], // Pothole
    status: 'in_progress',
    priority: 'high',
    location: {
      lat: 18.5089,
      lng: 73.9259,
      address: 'Near Shivaji Chowk, Hadapsar',
      landmark: 'Opposite SBI Bank',
      ward: 'Ward 15',
      zone: 'Zone 3',
    },
    images: ['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    assignedOfficerId: 'officer-1',
    assignedOfficerName: 'R.K. Pawar',
    departmentId: 'roads',
    departmentName: 'Roads (Raste Vibhag)',
    upvotes: 12,
    hasUpvoted: false,
    slaDeadline: '2026-03-14T10:32:00Z',
    slaBreached: false,
    slaRemainingHours: 18,
    timeline: [
      {
        id: 'tl-3',
        status: 'in_progress',
        message: 'Field team dispatched. Work will start today.',
        by: 'R.K. Pawar',
        byRole: 'officer',
        timestamp: '2026-03-11T09:00:00Z',
      },
      {
        id: 'tl-2',
        status: 'assigned',
        message: 'Complaint assigned to Roads Dept, Ward 15',
        by: 'System',
        byRole: 'admin',
        timestamp: '2026-03-10T11:00:00Z',
      },
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted by citizen',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-09T10:32:00Z',
      },
    ],
    comments: [
      {
        id: 'c-1',
        message: 'This is very dangerous, please fix ASAP. School children use this road.',
        by: 'Shankar Patil',
        byRole: 'citizen',
        isInternal: false,
        timestamp: '2026-03-10T14:15:00Z',
      },
      {
        id: 'c-2',
        message: 'Noted. We have scheduled repair for tomorrow morning.',
        by: 'R.K. Pawar',
        byRole: 'officer',
        isInternal: false,
        timestamp: '2026-03-10T16:30:00Z',
      },
    ],
    createdAt: '2026-03-09T10:32:00Z',
    updatedAt: '2026-03-11T09:00:00Z',
  },
  {
    id: 'complaint-2',
    displayId: 'CR-2026-00139',
    description: 'No water supply since yesterday morning. Multiple houses in this area are affected.',
    category: CATEGORIES[0], // Water
    subcategory: CATEGORIES[0].subcategories[0], // No Supply
    status: 'resolved',
    priority: 'medium',
    location: {
      lat: 18.5056,
      lng: 73.9234,
      address: 'Hadapsar Main Road, Near PMC School',
      ward: 'Ward 12',
      zone: 'Zone 3',
    },
    images: ['/placeholder.svg?height=300&width=400'],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    assignedOfficerId: 'officer-2',
    assignedOfficerName: 'Manoj Deshmukh',
    departmentId: 'water',
    departmentName: 'Water Supply (Jal Purti)',
    upvotes: 24,
    hasUpvoted: true,
    slaDeadline: '2026-03-07T14:00:00Z',
    slaBreached: false,
    timeline: [
      {
        id: 'tl-4',
        status: 'resolved',
        message: 'Water supply restored. Issue was due to pipeline repair work.',
        by: 'Manoj Deshmukh',
        byRole: 'officer',
        timestamp: '2026-03-07T11:00:00Z',
      },
      {
        id: 'tl-3',
        status: 'in_progress',
        message: 'Team investigating the issue.',
        by: 'Manoj Deshmukh',
        byRole: 'officer',
        timestamp: '2026-03-06T16:00:00Z',
      },
      {
        id: 'tl-2',
        status: 'assigned',
        message: 'Assigned to Water Supply department',
        by: 'System',
        byRole: 'admin',
        timestamp: '2026-03-06T14:30:00Z',
      },
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-06T14:00:00Z',
      },
    ],
    comments: [],
    createdAt: '2026-03-06T14:00:00Z',
    updatedAt: '2026-03-07T11:00:00Z',
    resolvedAt: '2026-03-07T11:00:00Z',
  },
  {
    id: 'complaint-3',
    displayId: 'CR-2026-00145',
    description: 'Street light not working for past 2 weeks. Area becomes very dark at night.',
    category: CATEGORIES[3], // Lights
    subcategory: CATEGORIES[3].subcategories[0], // Not Working
    status: 'pending',
    priority: 'medium',
    location: {
      lat: 18.5112,
      lng: 73.9301,
      address: 'Lane 5, Magarpatta City',
      ward: 'Ward 15',
      zone: 'Zone 3',
    },
    images: [],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    departmentId: 'electrical',
    departmentName: 'Electrical (Vidyut)',
    upvotes: 5,
    hasUpvoted: false,
    slaDeadline: '2026-03-14T16:00:00Z',
    slaBreached: false,
    slaRemainingHours: 48,
    timeline: [
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-11T16:00:00Z',
      },
    ],
    comments: [],
    createdAt: '2026-03-11T16:00:00Z',
    updatedAt: '2026-03-11T16:00:00Z',
  },
]

// Mock notifications
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'status_update',
    title: 'Status Updated',
    message: 'Your complaint CR-2026-00142 is now In Progress',
    complaintId: 'complaint-1',
    isRead: false,
    timestamp: '2026-03-11T09:00:00Z',
  },
  {
    id: 'notif-2',
    type: 'comment',
    title: 'New Comment',
    message: 'R.K. Pawar replied to your complaint',
    complaintId: 'complaint-1',
    isRead: false,
    timestamp: '2026-03-10T16:30:00Z',
  },
  {
    id: 'notif-3',
    type: 'status_update',
    title: 'Complaint Resolved',
    message: 'Your complaint CR-2026-00139 has been resolved. Please rate the resolution.',
    complaintId: 'complaint-2',
    isRead: true,
    timestamp: '2026-03-07T11:00:00Z',
  },
]

// Mock announcements
export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Water Supply Disruption Notice',
    content: 'Water supply will be disrupted in Zone 3 on 15th March for pipeline maintenance work. Please store water accordingly.',
    target: 'zone',
    targetId: 'Zone 3',
    isPublished: true,
    publishedAt: '2026-03-10T10:00:00Z',
    createdAt: '2026-03-10T09:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'New Garbage Collection Schedule',
    content: 'Starting from 1st April, garbage collection timing will be changed to 7 AM - 9 AM. Please cooperate.',
    target: 'all',
    isPublished: true,
    publishedAt: '2026-03-08T10:00:00Z',
    createdAt: '2026-03-08T09:00:00Z',
  },
]

// Mock dashboard stats
export const MOCK_CITIZEN_STATS: DashboardStats = {
  total: 8,
  pending: 3,
  inProgress: 2,
  resolved: 3,
  slaBreached: 0,
  avgResolutionDays: 2.1,
  satisfactionRating: 4.2,
}

export const MOCK_OFFICER_STATS: DashboardStats = {
  total: 45,
  pending: 12,
  inProgress: 8,
  resolved: 25,
  slaBreached: 3,
  avgResolutionDays: 1.8,
  satisfactionRating: 4.1,
}

export const MOCK_ADMIN_STATS: DashboardStats = {
  total: 15432,
  pending: 1234,
  inProgress: 567,
  resolved: 13631,
  slaBreached: 156,
  avgResolutionDays: 2.3,
  satisfactionRating: 4.0,
}

// Landing page stats
export const LANDING_STATS = {
  totalComplaints: 15432,
  resolvedPercent: 89,
  totalWards: 20,
  avgResolutionDays: 2.1,
}

// Mock officers for admin pages
export const MOCK_OFFICERS = [
  {
    id: 'officer-1',
    name: 'R.K. Pawar',
    email: 'rk.pawar@municipality.gov.in',
    phone: '+91 98765 43210',
    department: 'Roads',
    avatar: undefined,
    resolutionRate: 94,
    activeComplaints: 8,
  },
  {
    id: 'officer-2',
    name: 'Manoj Deshmukh',
    email: 'manoj.d@municipality.gov.in',
    phone: '+91 98765 43211',
    department: 'Water Supply',
    avatar: undefined,
    resolutionRate: 91,
    activeComplaints: 12,
  },
  {
    id: 'officer-3',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@municipality.gov.in',
    phone: '+91 98765 43212',
    department: 'Sanitation',
    avatar: undefined,
    resolutionRate: 88,
    activeComplaints: 6,
  },
  {
    id: 'officer-4',
    name: 'Amit Joshi',
    email: 'amit.j@municipality.gov.in',
    phone: '+91 98765 43213',
    department: 'Electrical',
    avatar: undefined,
    resolutionRate: 85,
    activeComplaints: 10,
  },
  {
    id: 'officer-5',
    name: 'Priya Mehta',
    email: 'priya.m@municipality.gov.in',
    phone: '+91 98765 43214',
    department: 'Health',
    avatar: undefined,
    resolutionRate: 92,
    activeComplaints: 4,
  },
]

// Full department objects for the departments management page
export const MOCK_DEPARTMENTS = [
  {
    id: 'roads',
    name: 'Roads Department',
    nameHindi: 'Raste Vibhag',
    headOfficerId: 'officer-1',
    headOfficerName: 'R.K. Pawar',
    contact: '+91 20 2612 0001',
    email: 'roads@municipality.gov.in',
    defaultSlaHours: 72,
    activeComplaints: 47,
    resolvedThisMonth: 198,
    slaCompliance: 92,
    officers: 8,
    isActive: true,
  },
  {
    id: 'water',
    name: 'Water Supply',
    nameHindi: 'Jal Purti',
    headOfficerId: 'officer-2',
    headOfficerName: 'Manoj Deshmukh',
    contact: '+91 20 2612 0002',
    email: 'water@municipality.gov.in',
    defaultSlaHours: 24,
    activeComplaints: 33,
    resolvedThisMonth: 156,
    slaCompliance: 88,
    officers: 6,
    isActive: true,
  },
  {
    id: 'sanitation',
    name: 'Sanitation',
    nameHindi: 'Swachhata',
    headOfficerId: 'officer-3',
    headOfficerName: 'Sneha Kulkarni',
    contact: '+91 20 2612 0003',
    email: 'sanitation@municipality.gov.in',
    defaultSlaHours: 24,
    activeComplaints: 21,
    resolvedThisMonth: 145,
    slaCompliance: 95,
    officers: 12,
    isActive: true,
  },
  {
    id: 'electrical',
    name: 'Electrical',
    nameHindi: 'Vidyut',
    headOfficerId: 'officer-4',
    headOfficerName: 'Amit Joshi',
    contact: '+91 20 2612 0004',
    email: 'electrical@municipality.gov.in',
    defaultSlaHours: 48,
    activeComplaints: 38,
    resolvedThisMonth: 98,
    slaCompliance: 78,
    officers: 5,
    isActive: true,
  },
  {
    id: 'health',
    name: 'Health',
    nameHindi: 'Swasthya',
    headOfficerId: 'officer-5',
    headOfficerName: 'Priya Mehta',
    contact: '+91 20 2612 0005',
    email: 'health@municipality.gov.in',
    defaultSlaHours: 48,
    activeComplaints: 9,
    resolvedThisMonth: 82,
    slaCompliance: 96,
    officers: 4,
    isActive: true,
  },
  {
    id: 'building',
    name: 'Building & Town Planning',
    nameHindi: 'Bhavan Nirman',
    headOfficerId: undefined,
    headOfficerName: 'Vacant',
    contact: '+91 20 2612 0006',
    email: 'building@municipality.gov.in',
    defaultSlaHours: 168,
    activeComplaints: 14,
    resolvedThisMonth: 42,
    slaCompliance: 82,
    officers: 3,
    isActive: true,
  },
  {
    id: 'garden',
    name: 'Garden & Trees',
    nameHindi: 'Udyan',
    headOfficerId: undefined,
    headOfficerName: 'Vacant',
    contact: '+91 20 2612 0007',
    email: 'garden@municipality.gov.in',
    defaultSlaHours: 120,
    activeComplaints: 7,
    resolvedThisMonth: 31,
    slaCompliance: 89,
    officers: 3,
    isActive: true,
  },
  {
    id: 'encroachment',
    name: 'Anti-Encroachment',
    nameHindi: 'Atikraman Nirmulan',
    headOfficerId: undefined,
    headOfficerName: 'Vacant',
    contact: '+91 20 2612 0008',
    email: 'encroachment@municipality.gov.in',
    defaultSlaHours: 96,
    activeComplaints: 11,
    resolvedThisMonth: 28,
    slaCompliance: 74,
    officers: 4,
    isActive: false,
  },
]

// Mock department stats for admin pages
export const MOCK_DEPARTMENT_STATS = [
  { name: 'Roads', total: 245, resolved: 198, pending: 32, slaCompliance: 92 },
  { name: 'Water Supply', total: 189, resolved: 156, pending: 22, slaCompliance: 88 },
  { name: 'Sanitation', total: 167, resolved: 145, pending: 15, slaCompliance: 95 },
  { name: 'Electrical', total: 134, resolved: 98, pending: 28, slaCompliance: 78 },
  { name: 'Health', total: 89, resolved: 82, pending: 5, slaCompliance: 96 },
  { name: 'Building', total: 56, resolved: 42, pending: 10, slaCompliance: 82 },
]

// Mock timeline for complaint detail
export const MOCK_TIMELINE = [
  {
    id: 'tl-3',
    status: 'in_progress',
    message: 'Field team dispatched. Work will start today.',
    by: 'R.K. Pawar',
    byRole: 'officer',
    timestamp: '2026-03-11T09:00:00Z',
  },
  {
    id: 'tl-2',
    status: 'assigned',
    message: 'Complaint assigned to Roads Dept, Ward 15',
    by: 'System',
    byRole: 'admin',
    timestamp: '2026-03-10T11:00:00Z',
  },
  {
    id: 'tl-1',
    status: 'pending',
    message: 'Complaint submitted by citizen',
    by: 'Shankar Patil',
    byRole: 'citizen',
    timestamp: '2026-03-09T10:32:00Z',
  },
]

// Mock users list for officer detail page
export const MOCK_USERS = [
  {
    id: 'user-1',
    name: 'Shankar Patil',
    phone: '+91 93264 58912',
    email: 'shankar.patil@email.com',
    avatar: undefined,
  },
  {
    id: 'user-2',
    name: 'Rajesh Kumar',
    phone: '+91 93264 58913',
    email: 'rajesh.kumar@email.com',
    avatar: undefined,
  },
]
