import { CATEGORIES } from './constants'

// Mock complaints
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const MOCK_COMPLAINTS: any[] = [
  {
    id: 'complaint-1',
    displayId: 'CR-2026-00142',
    description: 'There is a large pothole on the main road near Shivaji signal. Multiple accidents have happened here. Especially dangerous during rain.',
    category: CATEGORIES[1], // Roads
    subcategory: CATEGORIES[1].subcategories?.[0], // Pothole
    status: 'in_progress',
    priority: 'high',
    location: {
      lat: 18.5089,
      lng: 73.9259,
      address: 'Near Shivaji Chowk, Hadapsar',
      landmark: 'Opposite SBI Bank',
      ward: 'Ward 15',
      zone: 'Zone 3',
    },
    images: ['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    assignedOfficerId: 'officer-1',
    assignedOfficerName: 'R.K. Pawar',
    departmentId: 'roads',
    departmentName: 'Roads (Raste Vibhag)',
    upvotes: 12,
    hasUpvoted: false,
    slaDeadline: '2026-03-14T10:32:00Z',
    slaBreached: false,
    slaRemainingHours: 18,
    timeline: [
      {
        id: 'tl-3',
        status: 'in_progress',
        message: 'Field team dispatched. Work will start today.',
        by: 'R.K. Pawar',
        byRole: 'officer',
        timestamp: '2026-03-11T09:00:00Z',
      },
      {
        id: 'tl-2',
        status: 'assigned',
        message: 'Complaint assigned to Roads Dept, Ward 15',
        by: 'System',
        byRole: 'admin',
        timestamp: '2026-03-10T11:00:00Z',
      },
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted by citizen',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-09T10:32:00Z',
      },
    ],
    comments: [
      {
        id: 'c-1',
        message: 'This is very dangerous, please fix ASAP. School children use this road.',
        by: 'Shankar Patil',
        byRole: 'citizen',
        isInternal: false,
        timestamp: '2026-03-10T14:15:00Z',
      },
      {
        id: 'c-2',
        message: 'Noted. We have scheduled repair for tomorrow morning.',
        by: 'R.K. Pawar',
        byRole: 'officer',
        isInternal: false,
        timestamp: '2026-03-10T16:30:00Z',
      },
    ],
    createdAt: '2026-03-09T10:32:00Z',
    updatedAt: '2026-03-11T09:00:00Z',
  },
  {
    id: 'complaint-2',
    displayId: 'CR-2026-00139',
    description: 'No water supply since yesterday morning. Multiple houses in this area are affected.',
    category: CATEGORIES[0], // Water
    subcategory: CATEGORIES[0].subcategories?.[0], // No Supply
    status: 'resolved',
    priority: 'medium',
    location: {
      lat: 18.5056,
      lng: 73.9234,
      address: 'Hadapsar Main Road, Near PMC School',
      ward: 'Ward 12',
      zone: 'Zone 3',
    },
    images: ['/placeholder.svg?height=300&width=400'],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    assignedOfficerId: 'officer-2',
    assignedOfficerName: 'Manoj Deshmukh',
    departmentId: 'water',
    departmentName: 'Water Supply (Jal Purti)',
    upvotes: 24,
    hasUpvoted: true,
    slaDeadline: '2026-03-07T14:00:00Z',
    slaBreached: false,
    timeline: [
      {
        id: 'tl-4',
        status: 'resolved',
        message: 'Water supply restored. Issue was due to pipeline repair work.',
        by: 'Manoj Deshmukh',
        byRole: 'officer',
        timestamp: '2026-03-07T11:00:00Z',
      },
      {
        id: 'tl-3',
        status: 'in_progress',
        message: 'Team investigating the issue.',
        by: 'Manoj Deshmukh',
        byRole: 'officer',
        timestamp: '2026-03-06T16:00:00Z',
      },
      {
        id: 'tl-2',
        status: 'assigned',
        message: 'Assigned to Water Supply department',
        by: 'System',
        byRole: 'admin',
        timestamp: '2026-03-06T14:30:00Z',
      },
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-06T14:00:00Z',
      },
    ],
    comments: [],
    createdAt: '2026-03-06T14:00:00Z',
    updatedAt: '2026-03-07T11:00:00Z',
    resolvedAt: '2026-03-07T11:00:00Z',
  },
  {
    id: 'complaint-3',
    displayId: 'CR-2026-00145',
    description: 'Street light not working for past 2 weeks. Area becomes very dark at night.',
    category: CATEGORIES[3], // Lights
    subcategory: CATEGORIES[3].subcategories?.[0], // Not Working
    status: 'pending',
    priority: 'medium',
    location: {
      lat: 18.5112,
      lng: 73.9301,
      address: 'Lane 5, Magarpatta City',
      ward: 'Ward 15',
      zone: 'Zone 3',
    },
    images: [],
    citizenId: 'user-1',
    citizenName: 'Shankar Patil',
    departmentId: 'electrical',
    departmentName: 'Electrical (Vidyut)',
    upvotes: 5,
    hasUpvoted: false,
    slaDeadline: '2026-03-14T16:00:00Z',
    slaBreached: false,
    slaRemainingHours: 48,
    timeline: [
      {
        id: 'tl-1',
        status: 'pending',
        message: 'Complaint submitted',
        by: 'Shankar Patil',
        byRole: 'citizen',
        timestamp: '2026-03-11T16:00:00Z',
      },
    ],
    comments: [],
    createdAt: '2026-03-11T16:00:00Z',
    updatedAt: '2026-03-11T16:00:00Z',
  },
]
